
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wallet }
    username: ${DB_USER:root}
    password: ${DB_PASS:root}

server:
  port: 8080


